version: '2'
services:
  # jeecg-boot-mysql:
  #   build:
  #     context: ./jeecg-boot/db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_ROOT_HOST: '%'
  #     TZ: Asia/Shanghai
  #   restart: always
  #   container_name: jeecg-boot-mysql
  #   image: jeecg-boot-mysql
  #   command:
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_general_ci
  #     --explicit_defaults_for_timestamp=true
  #     --lower_case_table_names=1
  #     --max_allowed_packet=128M
  #     --default-authentication-plugin=caching_sha2_password
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - jeecg-boot

  jeecg-boot-pgsql:
    build:
      context: ./jeecg-boot/db_pgsql
    environment:
      POSTGRES_DB: jeecg-boot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Shanghai
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    container_name: jeecg-boot-pgsql
    image: jeecg-boot-pgsql
    ports:
      - 5432:5432
    volumes:
      - /opt/database/pgsql/data:/var/lib/postgresql/data
      - /opt/database/pgsql/logs:/var/log/postgresql
      - /opt/database/pgsql/backup:/opt/backup
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_wal_senders=0"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_directory=/var/log/postgresql"
      - "-c"
      - "log_filename=postgresql-%Y-%m-%d_%H%M%S.log"
      - "-c"
      - "log_rotation_age=1d"
      - "-c"
      - "log_rotation_size=100MB"
      - "-c"
      - "log_min_duration_statement=1000"
      - "-c"
      - "log_checkpoints=on"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "log_disconnections=on"
      - "-c"
      - "log_lock_waits=on"
      - "-c"
      - "log_temp_files=0"
      - "-c"
      - "log_autovacuum_min_duration=0"
      - "-c"
      - "log_error_verbosity=verbose"
    networks:
      - jeecg-boot

  jeecg-boot-redis:
    image: registry.cn-hangzhou.aliyuncs.com/jeecgdocker/redis:5.0
    ports:
      - 6379:6379
    restart: always
    hostname: jeecg-boot-redis
    container_name: jeecg-boot-redis
    networks:
      - jeecg-boot

  jeecg-boot-system:
    build:
      context: ./jeecg-boot/jeecg-module-system/jeecg-system-start
    restart: on-failure
    depends_on:
      - jeecg-boot-pgsql
      - jeecg-boot-redis
    container_name: jeecg-boot-system
    image: jeecg-boot-system
    hostname: jeecg-boot-system
    ports:
      - 8080:8080
    networks:
      - jeecg-boot
  jeecg-vue:
    build:
      context: ./jeecgboot-vue3
    container_name: jeecgboot-vue3-nginx
    image: jeecgboot-vue3
    depends_on:
      - jeecg-boot-system
    networks:
      - jeecg-boot
    ports:
      - 80:80

networks:
  jeecg-boot:
    name: jeecg_boot
