server:
  port: 7002
  
spring:
  application:
    name: jeecg-demo
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_ADDR:jeecg-boot-nacos:8848}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NS:}
        username: ${NACOS_USER:}
        password: ${NACOS_PWD:}
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NS:}
        username: ${NACOS_USER:}
        password: ${NACOS_PWD:}
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-${SPRING_PROFILES_ACTIVE:dev}.yaml